version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - tracing-network

  user-service:
    build: ./user-service
    ports:
      - "8080:8080"   
    environment:
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces
    depends_on:
      - jaeger
    networks:
      - tracing-network

  order-service:
    build: ./order-service
    ports:
      - "8081:8081" 
    environment:
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces
    depends_on:
      - jaeger
    networks:
      - tracing-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports:
      - "9200:9200"    
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false            # Deaktiviert die Anmeldung
      - xpack.security.enrollment.enabled=false # Verhindert die Token-Abfrage
      - xpack.security.http.ssl.enabled=false   # Deaktiviert HTTPS (wichtig für Codespaces)
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - tracing-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    # Logstash braucht eine Konfiguration, wie es die Daten von Spring empfängt
    command: >
      bash -c "echo 'input { tcp { port => 5044 codec => json } } output { elasticsearch { hosts => [\"http://elasticsearch:9200\"] index => \"springboot-logs-%{+YYYY.MM.dd}\" } }' > /usr/share/logstash/pipeline/logstash.conf && /usr/share/logstash/bin/logstash"
    networks:
      - tracing-network
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - tracing-network
    depends_on:
      - elasticsearch

networks:
  tracing-network:
    driver: bridge