spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Damit die URL in Codespaces funktioniert:
spring.h2.console.settings.web-allow-others=true

# Alle Actuator-Endpunkte freigeben (Vorsicht in Produktion, nur für Dev!)
management.endpoints.web.exposure.include=*

# Liveness und Readiness Probes explizit aktivieren
management.endpoint.health.probes.enabled=true

# Details anzeigen (z.B. ob die Datenbankverbindung steht)
management.endpoint.health.show-details=always

# Actuator-Endpunkte in Swagger UI anzeigen
springdoc.show-actuator=true