spring.application.name=order-service
server.port=8081

# Tracing Konfiguration (wie im User-Service)
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces

management.endpoints.web.exposure.include=*